#!/bin/sh 
export LC_NUMERIC="en_US.UTF-8"

domain=$1
domain_path=DATALAKE/$domain
mkdir -p $domain_path
tmp_file=$(mktemp)
timestamp=$(date +%s)
topics_json=$domain_path/$timestamp.json

shift

#echo "$@"
q="" # Query Variable
for input in "$@"
do
  q="$q""topic:$input+"
done
q=$(echo "$q" | rev | cut -c2- | rev) # remove the last '+'
url="https://api.github.com/search/repositories?q=$q" 

curl -sH "Accept: application/vnd.github.mercy-preview+json" https://api.github.com/search/repositories\?q\=$q > $tmp_file
mv $tmp_file $topics_json

topics=$(cat $topics_json |  jq '.items[].full_name' | head -10 | tr -s "\n" " ")   

for project in $topics
do
  project=$(echo $project | tr -d '"')
  git clone https://github.com/$project.git $domain_path/$project
  #echo "https://github.com/$project.git $domain_path/$project\n"
done
